from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
import os

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "index.md"

IGNORE_DIRS = {
    ".git",
    ".github",
    "scripts",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    ".idea",
    ".vscode",
}

IGNORE_FILES = {
    "index.md",
    "generate_index.py",
    "update-index.yml",
}

folders = []
root_files = []
markdown_files = []

for current_path, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

    rel_dir = Path(current_path).relative_to(ROOT)

    if rel_dir != Path("."):
        folders.append(rel_dir.as_posix())

    for file in files:
        if file in IGNORE_FILES:
            continue

        file_path = Path(current_path) / file
        relative = file_path.relative_to(ROOT)

        if rel_dir == Path("."):
            root_files.append(relative.as_posix())

        if file.endswith(".md"):
            markdown_files.append(relative.as_posix())

folders.sort()
root_files.sort()
markdown_files.sort()

now = datetime.now(ZoneInfo("Asia/Dhaka"))
last_updated = now.strftime("%d %B %Y, %I:%M %p (BST)")    f.write("> 🤖 This file is automatically generated. Do not edit manually.\n\n")
    f.write(f"**Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n")

    f.write("## 📂 Available Documentation\n\n")

    if rows:
        f.write("| Folder | README |\n")
        f.write("|--------|--------|\n")

        for folder, link in rows:
            f.write(f"| `{folder}` | [README]({link}) |\n")
    else:
        f.write("_No README.md files found._\n")

    f.write("\n---\n\n")
    f.write("## 📄 Root Files\n\n")

    for file in sorted(ROOT.iterdir()):
        if file.is_file():
            if file.name == "index.md":
                continue
            f.write(f"- [{file.name}](./{file.name})\n")

print("✅ index.md generated successfully.")
