from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
import os

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "index.md"

IGNORE_DIRS = {
    ".git",
    ".github",
    "scripts",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    ".idea",
    ".vscode",
}

IGNORE_FILES = {
    "index.md",
    "generate_index.py",
    "update-index.yml",
}

folders = []
root_files = []
markdown_files = []

for current_path, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

    rel_dir = Path(current_path).relative_to(ROOT)

    if rel_dir != Path("."):
        folders.append(rel_dir.as_posix())

    for file in files:
        if file in IGNORE_FILES:
            continue

        file_path = Path(current_path) / file
        relative = file_path.relative_to(ROOT)

        if rel_dir == Path("."):
            root_files.append(relative.as_posix())

        if file.endswith(".md"):
            markdown_files.append(relative.as_posix())

folders.sort()
root_files.sort()
markdown_files.sort()

now = datetime.now(ZoneInfo("Asia/Dhaka"))
last_updated = now.strftime("%d %B %Y, %I:%M %p (BST)")    f.write("> 🤖 This file is automatically generated. Do not edit manually.\n\n")
    f.write(f"**Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n")

    f.write("## 📂 Available Documentation\n\n")

    if rows:
        f.write("| Folder | README |\n")
        f.write("|--------|--------|\n")

        for folder, link in rows:
            f.write(f"| `{folder}` | [README]({link}) |\n")
    else:
        f.write("_No README.md files found._\n")

    f.write("\n---\n\n")
    f.write("## 📄 Root Files\n\n")

    for file in sorted(ROOT.iterdir()):
        if file.is_file():
            if file.name == "index.md":
                continue
            f.write(f"- [{file.name}](./{file.name})\n")

print("✅ index.md generated successfully.")
with open(OUTPUT, "w", encoding="utf-8") as f:

    f.write("# 📚 Repository Index\n\n")
    f.write("> 🤖 This file is automatically generated.\n\n")

    f.write(f"**🕒 Last Updated:** {last_updated}\n\n")

    f.write("## 📊 Repository Statistics\n\n")
    f.write(f"- 📁 Folders: **{len(folders)}**\n")
    f.write(f"- 📄 Markdown Files: **{len(markdown_files)}**\n")
    f.write(f"- 📂 Root Files: **{len(root_files)}**\n\n")

    f.write("---\n\n")

    f.write("## 📂 Documentation\n\n")

    if markdown_files:
        current_folder = ""

        for file in markdown_files:
            path = Path(file)

            folder = path.parent.as_posix()

            if folder == ".":
                folder = "Root"

            if folder != current_folder:
                current_folder = folder
                f.write(f"### 📁 {folder}\n\n")

            f.write(f"- [{path.name}]({file})\n")

        f.write("\n")
    else:
        f.write("_No Markdown files found._\n\n")

    f.write("---\n\n")

    f.write("## 📄 Root Files\n\n")

    if root_files:
        for file in root_files:
            f.write(f"- [{file}]({file})\n")
    else:
        f.write("_No root files found._\n")
            f.write("\n---\n\n")

    f.write("## 🌳 Repository Structure\n\n")

    def print_tree(path, indent=""):
        items = sorted(
            [p for p in path.iterdir()
             if p.name not in IGNORE_DIRS
             and p.name not in IGNORE_FILES],
            key=lambda x: (x.is_file(), x.name.lower())
        )

        for item in items:
            if item.is_dir():
                f.write(f"{indent}- 📁 **{item.name}**\n")
                print_tree(item, indent + "  ")
            else:
                relative = item.relative_to(ROOT).as_posix()
                f.write(f"{indent}- 📄 [{item.name}]({relative})\n")

    print_tree(ROOT)

    f.write("\n---\n\n")

    f.write("## 🔗 Quick Links\n\n")

    if (ROOT / "README.md").exists():
        f.write("- [📘 Main README](README.md)\n")

    f.write("- [📚 Repository Index](index.md)\n")

    f.write("\n---\n\n")

    f.write(
        "<sub>🤖 This file is automatically generated by GitHub Actions. "
        "Do not edit manually.</sub>\n"
    )

print("✅ index.md generated successfully.")
