from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "index.md"

IGNORE_DIRS = {
    ".git",
    ".github",
    "__pycache__",
    "node_modules",
    ".venv",
    "venv",
    ".idea",
    ".vscode",
}

rows = []

for readme in sorted(ROOT.rglob("README.md")):
    if readme == ROOT / "README.md":
        continue

    rel = readme.relative_to(ROOT)
    parts = rel.parts

    if any(part in IGNORE_DIRS for part in parts):
        continue

    folder = rel.parent.as_posix()
    link = rel.as_posix()

    rows.append((folder, link))

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("# 📚 Repository Index\n\n")
    f.write("> 🤖 This file is automatically generated. Do not edit manually.\n\n")
    f.write(f"**Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n")

    f.write("## 📂 Available Documentation\n\n")

    if rows:
        f.write("| Folder | README |\n")
        f.write("|--------|--------|\n")

        for folder, link in rows:
            f.write(f"| `{folder}` | [README]({link}) |\n")
    else:
        f.write("_No README.md files found._\n")

    f.write("\n---\n\n")
    f.write("## 📄 Root Files\n\n")

    for file in sorted(ROOT.iterdir()):
        if file.is_file():
            if file.name == "index.md":
                continue
            f.write(f"- [{file.name}](./{file.name})\n")

print("✅ index.md generated successfully.")
